name: citadel
root: .

on_project_start: docker start test-db

windows:
  - services:
      root: ./
      panes:
        - api:
          - go run cmd/citadel/main.go web
        - yarn:
          - cd frontend
          - yarn start
  - web/editor:
      root: ./frontend
      panes:
        - vim src/index.tsx
  - api/editor:
      root: ./
      panes:
        - vim cmd/citadel/main.go
  - database:
      root: ./
      panes:
        - pgcli postgres://postgres:test@localhost:5432/citadel
