version: "3"
services:
  web:
    image: taskcafe/taskcafe:latest
    # build: .
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    networks:
      - taskcafe-test
    environment:
      TASKCAFE_DATABASE_HOST: postgres
      TASKCAFE_MIGRATE: "true"
    volumes:
      - taskcafe-uploads:/root/uploads
      
  postgres:
    image: postgres:12.3-alpine
    restart: always
    networks:
      - taskcafe-test
    environment:
      POSTGRES_USER: taskcafe
      POSTGRES_PASSWORD: taskcafe_test
      POSTGRES_DB: taskcafe
    volumes:
      - taskcafe-postgres:/var/lib/postgresql/data

volumes:
  taskcafe-postgres:
    external: false
  taskcafe-uploads:
    external: false

networks:
  taskcafe-test:
    driver: bridge
