// Code generated by sqlc. DO NOT EDIT.
// source: label_color.sql

package pg

import (
	"context"

	"github.com/google/uuid"
)

const getLabelColorByID = `-- name: GetLabelColorByID :one
SELECT label_color_id, color_hex, position FROM label_color WHERE label_color_id = $1
`

func (q *Queries) GetLabelColorByID(ctx context.Context, labelColorID uuid.UUID) (LabelColor, error) {
	row := q.db.QueryRowContext(ctx, getLabelColorByID, labelColorID)
	var i LabelColor
	err := row.Scan(&i.LabelColorID, &i.ColorHex, &i.Position)
	return i, err
}
