extend type Subscription {
    notificationAdded: Notified!
}

extend type Query {
  notifications: [Notified!]!
}

enum ActionType {
  TASK_MEMBER_ADDED
}

type NotificationData {
  key: String!
  value: String!
}

type NotificationCausedBy {
  fullname: String!
  username: String!
  id: ID!
}

type Notification {
  id: ID!
  actionType: ActionType!
  causedBy: NotificationCausedBy!
  data: [NotificationData!]!
  createdAt: Time!
}

type Notified {
  id: ID!
  notification: Notification!
  read: Boolean!
  readAt: Time
}

