// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) (AccessToken, error)
	CreateUserAccount(ctx context.Context, arg CreateUserAccountParams) (UserAccount, error)
	DeleteAccessToken(ctx context.Context, token string) error
	GetAccessToken(ctx context.Context, token string) (AccessToken, error)
	GetUserAccountByID(ctx context.Context, userID uuid.UUID) (UserAccount, error)
	GetUserAccountByUsername(ctx context.Context, username string) (UserAccount, error)
	GetUserAccounts(ctx context.Context) ([]UserAccount, error)
	HasAnyUserAccount(ctx context.Context) (bool, error)
}

var _ Querier = (*Queries)(nil)
